server:
  port: ${port:8081}
spring:
  eai:
    ad:
      loginUri: http://192.168.100.48:9093/ad-gateways/verify1
      clientId: 8C21EBEEB1AA3FBFE05400144FFBD319
      applicationID: PRJ1
      userId: ibofdev01
      password: da82edc6dcc1af30
      key: 123456789013245678901234
  security:
    oauth2:
      server: 
        url: http://127.0.0.1:12081/oauth/token
      rest:
        timeout:
          read: 60000
          connection: 60000
      clientId: javainuse-client
      clientSecret: javainuse-secret
      authorize-grant-type: password,refresh_token
      accessTokenValiditySeconds: 43200
      refreshTokenValiditySeconds: 2592000
    jwt:
      signingkey: pakar123
  dataSource: 
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.100.48:5432/postgres
    username: postgres
    password: password
##    hikari:
##      connectionTimeout: 20000
##      maximumPoolSize: 5   
#    
#
## Hibernate ddl auto (create, create-drop, update)
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQL10Dialect   