apiVersion: v1
kind: Service
metadata:
  name: pakar-oauth-server
  labels:
    app: pakar-oauth-server
spec:
  selector:
    app: pakar-oauth-server
  ports:
  - name: port-oauth-server
    protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 12081
  type: NodePort
  externalTrafficPolicy: Cluster