server:
  port: ${port:8083}
spring:
  eai:
    ad:
      loginUri: http://localhost:9093/ad-gateways/verify1
      clientId: 8C21EBEEB1AA3FBFE05400144FFBD319
      applicationID: PRJ1
      userId: ibofdev01
      password: da82edc6dcc1af30
      key: 123456789013245678901234
  security:
    oauth2:
      server: 
        url: http://192.168.100.48:8083/oauth/token
      rest:
        timeout:
          read: 60000
          connection: 60000
      clientId: javainuse-client
      clientSecret: javainuse-secret
      authorize-grant-type: password, refresh_token
      accessTokenValiditySeconds: 600
      refreshTokenValiditySeconds: 21600
    jwt:
      signingkey: pakar123
  dataSource: 
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.100.48:5432/postgres
    username: postgres
    password: password
##    hikari:
##      connectionTimeout: 20000
##      maximumPoolSize: 5   
#    
#
## Hibernate ddl auto (create, create-drop, update)
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy  
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
#
## Use spring.jpa.properties.* for Hibernate native properties (the prefix is
## stripped before adding them to the entity manager)
#
## The SQL dialect makes Hibernate generate better SQL for the chosen database
##spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
##  spring:
##    datasource:
##      driver-class-name=org.hibernate.dialect.PostgreSQL10Dialect
#      